// Localhost
###
GET http://localhost:3000/recipes
###
GET http://localhost:3000/recipes/632bf13d8d980b27b004bd05
###
GET http://localhost:3000/recipes/632bf1fd8d980b27b004bd06
###
GET http://localhost:3000/recipes/632bf2428d980b27b004bd07


// Render
###
GET https://recipe-book-project.onrender.com/recipes
###
GET https://recipe-book-project.onrender.com/recipes/632bf13d8d980b27b004bd05
###
GET https://recipe-book-project.onrender.com/recipes/632bf1fd8d980b27b004bd06
###
GET https://recipe-book-project.onrender.com/recipes/632bf2428d980b27b004bd07


// Localhost
### Create contact 
POST http://localhost:3000/recipes HTTP/1.1
content-type: application/json

# {
#     "recipeName": "",
#     "ingredients": "",
#     "instructions": "",
#     "prepareTime": ""
# }

### Updated contact 
PUT http://localhost:3000/recipes/632bf2428d980b27b004bd07 HTTP/1.1
content-type: application/json

# {
#     "recipeName": "",
#     "ingredients": "",
#     "instructions": "",
#     "prepareTime": ""
# }

### Delete contact 
DELETE http://localhost:3000/recipes/6333bdc36c0f81f076ae4c2b HTTP/1.1



// Render
### Create contact 
POST https://recipe-book-project.onrender.com/recipes HTTP/1.1
content-type: application/json

# {
#     "recipeName": "",
#     "ingredients": "",
#     "instructions": "",
#     "prepareTime": ""
# }

### Updated contact 
PUT https://recipe-book-project.onrender.com/recipes/6333c1dfce9aaeddf709b441 HTTP/1.1
content-type: application/json

{
    "recipeName": "",
    "ingredients": "",
    "instructions": "",
    "prepareTime": ""
}

### Delete contact 
DELETE https://recipe-book-project.onrender.com/recipes/6333c1dfce9aaeddf709b441 HTTP/1.1
