// Localhost
###
GET http://localhost:8080/recipes
###
GET http://localhost:8080/recipes/6349b6c12689d09aa05383f5
###
GET http://localhost:8080/recipes/6349b6c12689d09aa05383f5
###
GET http://localhost:8080/recipes/6349b6c12689d09aa05383f5


// Render
###
GET https://recipe-book-project.onrender.com/recipes
###
GET https://recipe-book-project.onrender.com/recipes/6349b6c12689d09aa05383f5
###
GET https://recipe-book-project.onrender.com/recipes/6349b6c12689d09aa05383f5
###
GET https://recipe-book-project.onrender.com/recipes/6349b6c12689d09aa05383f5


// Localhost
### Create user 
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "userName": "sp",
    "email": "Yepme@gmail.com",
    "password": "Sood1234?"
}

### Create recipe 
POST http://localhost:8080/recipes HTTP/1.1
content-type: application/json

{
    "recipeName": "",
    "ingredients": "",
    "instructions": "",
    "prepareTime": "",
    "tags": ""
}

### Updated recipe 
PUT http://localhost:8080/recipes/6349b6c12689d09aa05383f5 HTTP/1.1
content-type: application/json

# {
#     "recipeName": "",
#     "ingredients": "",
#     "instructions": "",
#     "prepareTime": "",
#     "tags": ""
# }

### Delete recipe 
DELETE http://localhost:8080/recipes/6349b6c12689d09aa05383f5 HTTP/1.1



// Render
### Create recipe 
POST https://recipe-book-project.onrender.com/recipes HTTP/1.1
content-type: application/json

{
    "recipeName": "Blueberry Smoothie",
    "ingredients": [
        {
            "quantity": "1 cup",
            "name": "almond milk or oatmilk",
            "type": "Drinks"
        },
        {
            "quantity": "2 medium",
            "name": "bananas (frozen)",
            "type": "Fruit"
        },
        {
            "quantity": "3 cup",
            "name": "blueberries (frozen)",
            "type": "Fruit"
        },
        {
            "quantity": "1 T",
            "name": "maple syrup or honey",
            "type": "Sweetener"
        }
    ],
    "instructions": [
        "Add all ingredients into a blender.",
        "Blend on low for about 20 seconds, and then turn up speed to medium high until the mixture is smooth.",
        "Add extra sweetener or milk if needed.",
        "Optional: add a cup or more of spinach"
    ],
    "prepareTime": "5 minutes",
    "tags": [
        "breakfast",
        "dessert",
        "vegan",
        "dairy free"
    ]
}

### Updated recipe 
PUT https://recipe-book-project.onrender.com/recipes/6349b6c12689d09aa05383f5 HTTP/1.1
content-type: application/json

# {
#     "recipeName": "",
#     "ingredients": "",
#     "instructions": "",
#     "prepareTime": "",
#     "tags": ""
# }

### Delete recipe 
DELETE https://recipe-book-project.onrender.com/recipes/6349b6c12689d09aa05383f5 HTTP/1.1


### Create user 
PUT http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "userName": "Supper97",
    "email": "supper97@gmail.com",
    "password": "Soyou97!"
}

### Create user 
DELETE http://localhost:8080/Sup12 HTTP/1.1
content-type: application/json


### Delete user
PUT https://recipe-book-project.onrender.com/users/Sup12 HTTP/1.1

### Delete user
DELETE https://recipe-book-project.onrender.com/users/Sup12 HTTP/1.1